workflows:
  ios-workflow:
    name: Expo iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      node: 20  # <--- Update this from 18 to 20
      groups:
        - credentials
      vars:
        CI: "true"

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Generate Native iOS Project
        script: |
          npx expo prebuild --platform ios --no-install

      - name: Install CocoaPods Remotely
        script: |
          cd ios && pod install

      - name: Compile Standalone Development App
        script: |
          xcodebuild -workspace ios/gym1111.xcworkspace \
                     -scheme gym1111 \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/ios/gym1111.xcarchive \
                     archive \
                     CODE_SIGNING_ALLOWED=NO

    artifacts:
      - $CM_BUILD_DIR/ios/*.xcarchive
      - ios/build/**/*.app